---
title: "ASCellCycle"
author: "Kwame Forbes"
date: "10/25/2022"
output: html_document
---

loading dependencies
```{r}
library(dplyr)
library(tidyr)
library(phateR)
library(fCI)
```

variables
```{r}
IncLevelvar = 0.05
FDR.variable = 0.05
coverage = 50
```



functions
```{r}
f <- function(x, ...) {
  abs(max(x) -min(x))
}
```


RI JC
```{r}
Cellcycle_RI_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/RI.MATS.JC.txt",header = T)
Cellcycle_RI_JC <- as.data.frame(Cellcycle_RI_JC)
Cellcycle_RI_JC$Key <- paste(Cellcycle_RI_JC$ID,Cellcycle_RI_JC$GeneID,sep = "_")
rownames(Cellcycle_RI_JC) <- Cellcycle_RI_JC$Key
AS = as.data.frame(rep("RI",dim(Cellcycle_RI_JC)[1]))
names(AS)[names(AS) == 'rep("RI", dim(Cellcycle_RI_JC)[1])'] <- "Event"
Cellcycle_RI_JC = cbind(Cellcycle_RI_JC,AS)

Cellcycle_RI_JC <- separate(Cellcycle_RI_JC, col = IJC_SAMPLE_1, into = c("IJC_TP_1","IJC_TP_2","IJC_TP_3","IJC_TP_6","IJC_TP_7",
                                                                          "IJC_TP_8","IJC_TP_12","IJC_TP_13","IJC_TP_14"),sep = ",",remove = T)

Cellcycle_RI_JC <- separate(Cellcycle_RI_JC, col = SJC_SAMPLE_1, into = c("SJC_TP_1","SJC_TP_2","SJC_TP_3","SJC_TP_6","SJC_TP_7",
                                                                          "SJC_TP_8","SJC_TP_12","SJC_TP_13","SJC_TP_14"),sep = ",",remove = T)

Cellcycle_RI_JC <- separate(Cellcycle_RI_JC, col = IJC_SAMPLE_2, into = c("IJC_TP_4","IJC_TP_5","IJC_TP_9","IJC_TP_10","IJC_TP_11"),sep = ",",remove = T)

Cellcycle_RI_JC <- separate(Cellcycle_RI_JC, col = SJC_SAMPLE_2, into = c("SJC_TP_4","SJC_TP_5","SJC_TP_9","SJC_TP_10","SJC_TP_11"),sep = ",",remove = T)

Cellcycle_RI_JC[11:40] <- as.numeric(unlist(Cellcycle_RI_JC[11:40]))

Cellcycle_RI_JC <- separate(Cellcycle_RI_JC, col = IncLevel1, into = c("PSI_TP_1","PSI_TP_2","PSI_TP_3","PSI_TP_6","PSI_TP_7",
                                                                       "PSI_TP_8","PSI_TP_12","PSI_TP_13","PSI_TP_14"),sep = ",",remove = T)

Cellcycle_RI_JC <- separate(Cellcycle_RI_JC, col = IncLevel2, into = c("PSI_TP_4","PSI_TP_5","PSI_TP_9","PSI_TP_10","PSI_TP_11"),sep = ",",remove = T)

Cellcycle_RI_JC[45:58] <- as.numeric(unlist(Cellcycle_RI_JC[45:58]))

Cellcycle_RI_JC = unite(Cellcycle_RI_JC,"Position",c(4:11),sep = ":",remove = T)
Cellcycle_RI_JC = na.omit(Cellcycle_RI_JC)
Cellcycle_RI_JC$PSIDiff <- (apply(Cellcycle_RI_JC[38:51], MARGIN =  1, f,))
Cellcycle_RI_JC = unite(Cellcycle_RI_JC,"EVENT",c(3,4),sep = "_", remove = T)
Cellcycle_RI_JC = subset(Cellcycle_RI_JC,select = c(53,3,2,5:7,23,24,8:10,25:27,11:13,
                                                    14:16,28,29,17:19,30:32,20:22,
                                                    37:39,46,47,40:42,48:50,43:45,36,54))

```

RI Filtering by average reads
```{r}
Cellcycle_RI_JC <- subset(Cellcycle_RI_JC,
                         apply(Cellcycle_RI_JC[c(4,18)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(5,19)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(6,20)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(7,21)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(8,22)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(9,23)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(10,24)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(11,25)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(12,26)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(13,27)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(14,28)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(15,29)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(16,30)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_RI_JC[c(17,31)], MARGIN =  1,mean)>=coverage)

```



SE JC
```{r}
Cellcycle_SE_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/SE.MATS.JC.txt",header = T)
Cellcycle_SE_JC <- as.data.frame(Cellcycle_SE_JC)
Cellcycle_SE_JC$Key <- paste(Cellcycle_SE_JC$ID,Cellcycle_SE_JC$GeneID,sep = "_")
rownames(Cellcycle_SE_JC) <- Cellcycle_SE_JC$Key
AS = as.data.frame(rep("SE",dim(Cellcycle_SE_JC)[1]))
names(AS)[names(AS) == 'rep("SE", dim(Cellcycle_SE_JC)[1])'] <- "Event"
Cellcycle_SE_JC = cbind(Cellcycle_SE_JC,AS)

Cellcycle_SE_JC <- separate(Cellcycle_SE_JC, col = IJC_SAMPLE_1, into = c("IJC_TP_1","IJC_TP_2","IJC_TP_3","IJC_TP_6","IJC_TP_7",
                                                                          "IJC_TP_8","IJC_TP_12","IJC_TP_13","IJC_TP_14"),sep = ",",remove = T)

Cellcycle_SE_JC <- separate(Cellcycle_SE_JC, col = SJC_SAMPLE_1, into = c("SJC_TP_1","SJC_TP_2","SJC_TP_3","SJC_TP_6","SJC_TP_7",
                                                                          "SJC_TP_8","SJC_TP_12","SJC_TP_13","SJC_TP_14"),sep = ",",remove = T)

Cellcycle_SE_JC <- separate(Cellcycle_SE_JC, col = IJC_SAMPLE_2, into = c("IJC_TP_4","IJC_TP_5","IJC_TP_9","IJC_TP_10","IJC_TP_11"),sep = ",",remove = T)

Cellcycle_SE_JC <- separate(Cellcycle_SE_JC, col = SJC_SAMPLE_2, into = c("SJC_TP_4","SJC_TP_5","SJC_TP_9","SJC_TP_10","SJC_TP_11"),sep = ",",remove = T)

Cellcycle_SE_JC[11:40] <- as.numeric(unlist(Cellcycle_SE_JC[11:40]))

Cellcycle_SE_JC <- separate(Cellcycle_SE_JC, col = IncLevel1, into = c("PSI_TP_1","PSI_TP_2","PSI_TP_3","PSI_TP_6","PSI_TP_7",
                                                                       "PSI_TP_8","PSI_TP_12","PSI_TP_13","PSI_TP_14"),sep = ",",remove = T)

Cellcycle_SE_JC <- separate(Cellcycle_SE_JC, col = IncLevel2, into = c("PSI_TP_4","PSI_TP_5","PSI_TP_9","PSI_TP_10","PSI_TP_11"),sep = ",",remove = T)

Cellcycle_SE_JC[45:58] <- as.numeric(unlist(Cellcycle_SE_JC[45:58]))

Cellcycle_SE_JC = unite(Cellcycle_SE_JC,"Position",c(4:11),sep = ":",remove = T)
Cellcycle_SE_JC = na.omit(Cellcycle_SE_JC)
Cellcycle_SE_JC$PSIDiff <- (apply(Cellcycle_SE_JC[38:51], MARGIN =  1, f,))
Cellcycle_SE_JC = unite(Cellcycle_SE_JC,"EVENT",c(3,4),sep = "_", remove = T)
Cellcycle_SE_JC = subset(Cellcycle_SE_JC,select = c(53,3,2,5:7,23,24,8:10,25:27,11:13,
                                                    14:16,28,29,17:19,30:32,20:22,
                                                    37:39,46,47,40:42,48:50,43:45,36,54))
```

SE Filtering by average reads
```{r}
Cellcycle_SE_JC <- subset(Cellcycle_SE_JC,
                         apply(Cellcycle_SE_JC[c(4,18)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(5,19)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(6,20)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(7,21)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(8,22)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(9,23)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(10,24)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(11,25)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(12,26)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(13,27)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(14,28)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(15,29)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(16,30)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_SE_JC[c(17,31)], MARGIN =  1,mean)>=coverage)
```

 

A3SS
```{r}
Cellcycle_A3SS_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/A3SS.MATS.JC.txt",header = T)
Cellcycle_A3SS_JC <- as.data.frame(Cellcycle_A3SS_JC)
Cellcycle_A3SS_JC$Key <- paste(Cellcycle_A3SS_JC$ID,Cellcycle_A3SS_JC$GeneID,sep = "_")
rownames(Cellcycle_A3SS_JC) <- Cellcycle_A3SS_JC$Key
AS = as.data.frame(rep("A3SS",dim(Cellcycle_A3SS_JC)[1]))
names(AS)[names(AS) == 'rep("A3SS", dim(Cellcycle_A3SS_JC)[1])'] <- "Event"
Cellcycle_A3SS_JC = cbind(Cellcycle_A3SS_JC,AS)

Cellcycle_A3SS_JC <- separate(Cellcycle_A3SS_JC, col = IJC_SAMPLE_1, into = c("IJC_TP_1","IJC_TP_2","IJC_TP_3","IJC_TP_6","IJC_TP_7",
                                                                              "IJC_TP_8","IJC_TP_12","IJC_TP_13","IJC_TP_14"),sep = ",",remove = T)

Cellcycle_A3SS_JC <- separate(Cellcycle_A3SS_JC, col = SJC_SAMPLE_1, into = c("SJC_TP_1","SJC_TP_2","SJC_TP_3","SJC_TP_6","SJC_TP_7",
                                                                              "SJC_TP_8","SJC_TP_12","SJC_TP_13","SJC_TP_14"),sep = ",",remove = T)

Cellcycle_A3SS_JC <- separate(Cellcycle_A3SS_JC, col = IJC_SAMPLE_2, into = c("IJC_TP_4","IJC_TP_5","IJC_TP_9","IJC_TP_10","IJC_TP_11"),sep = ",",remove = T)

Cellcycle_A3SS_JC <- separate(Cellcycle_A3SS_JC, col = SJC_SAMPLE_2, into = c("SJC_TP_4","SJC_TP_5","SJC_TP_9","SJC_TP_10","SJC_TP_11"),sep = ",",remove = T)

Cellcycle_A3SS_JC[11:40] <- as.numeric(unlist(Cellcycle_A3SS_JC[11:40]))

Cellcycle_A3SS_JC <- separate(Cellcycle_A3SS_JC, col = IncLevel1, into = c("PSI_TP_1","PSI_TP_2","PSI_TP_3","PSI_TP_6","PSI_TP_7",
                                                                           "PSI_TP_8","PSI_TP_12","PSI_TP_13","PSI_TP_14"),sep = ",",remove = T)

Cellcycle_A3SS_JC <- separate(Cellcycle_A3SS_JC, col = IncLevel2, into = c("PSI_TP_4","PSI_TP_5","PSI_TP_9","PSI_TP_10","PSI_TP_11"),sep = ",",remove = T)

Cellcycle_A3SS_JC[45:58] <- as.numeric(unlist(Cellcycle_A3SS_JC[45:58]))

Cellcycle_A3SS_JC = unite(Cellcycle_A3SS_JC,"Position",c(4:11),sep = ":",remove = T)
Cellcycle_A3SS_JC = na.omit(Cellcycle_A3SS_JC)
Cellcycle_A3SS_JC$PSIDiff <- (apply(Cellcycle_A3SS_JC[38:51], MARGIN =  1, f,))
Cellcycle_A3SS_JC = unite(Cellcycle_A3SS_JC,"EVENT",c(3,4),sep = "_", remove = T)
Cellcycle_A3SS_JC = subset(Cellcycle_A3SS_JC,select = c(53,3,2,5:7,23,24,8:10,25:27,11:13,
                                                    14:16,28,29,17:19,30:32,20:22,
                                                    37:39,46,47,40:42,48:50,43:45,36,54))
```


A3SS Filtering by average reads
```{r}
Cellcycle_A3SS_JC <- subset(Cellcycle_A3SS_JC,
                         apply(Cellcycle_A3SS_JC[c(4,18)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(5,19)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(6,20)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(7,21)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(8,22)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(9,23)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(10,24)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(11,25)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(12,26)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(13,27)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(14,28)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(15,29)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(16,30)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A3SS_JC[c(17,31)], MARGIN =  1,mean)>=coverage)
```


A5SS 
```{r}
Cellcycle_A5SS_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/A5SS.MATS.JC.txt",header = T)
Cellcycle_A5SS_JC <- as.data.frame(Cellcycle_A5SS_JC)
Cellcycle_A5SS_JC$Key <- paste(Cellcycle_A5SS_JC$ID,Cellcycle_A5SS_JC$GeneID,sep = "_")
rownames(Cellcycle_A5SS_JC) <- Cellcycle_A5SS_JC$Key
AS = as.data.frame(rep("A3SS",dim(Cellcycle_A5SS_JC)[1]))
names(AS)[names(AS) == 'rep("A3SS", dim(Cellcycle_A5SS_JC)[1])'] <- "Event"
Cellcycle_A5SS_JC = cbind(Cellcycle_A5SS_JC,AS)

Cellcycle_A5SS_JC <- separate(Cellcycle_A5SS_JC, col = IJC_SAMPLE_1, into = c("IJC_TP_1","IJC_TP_2","IJC_TP_3","IJC_TP_6","IJC_TP_7",
                                                                              "IJC_TP_8","IJC_TP_12","IJC_TP_13","IJC_TP_14"),sep = ",",remove = T)

Cellcycle_A5SS_JC <- separate(Cellcycle_A5SS_JC, col = SJC_SAMPLE_1, into = c("SJC_TP_1","SJC_TP_2","SJC_TP_3","SJC_TP_6","SJC_TP_7",
                                                                              "SJC_TP_8","SJC_TP_12","SJC_TP_13","SJC_TP_14"),sep = ",",remove = T)

Cellcycle_A5SS_JC <- separate(Cellcycle_A5SS_JC, col = IJC_SAMPLE_2, into = c("IJC_TP_4","IJC_TP_5","IJC_TP_9","IJC_TP_10","IJC_TP_11"),sep = ",",remove = T)

Cellcycle_A5SS_JC <- separate(Cellcycle_A5SS_JC, col = SJC_SAMPLE_2, into = c("SJC_TP_4","SJC_TP_5","SJC_TP_9","SJC_TP_10","SJC_TP_11"),sep = ",",remove = T)

Cellcycle_A5SS_JC[11:40] <- as.numeric(unlist(Cellcycle_A5SS_JC[11:40]))

Cellcycle_A5SS_JC <- separate(Cellcycle_A5SS_JC, col = IncLevel1, into = c("PSI_TP_1","PSI_TP_2","PSI_TP_3","PSI_TP_6","PSI_TP_7",
                                                                           "PSI_TP_8","PSI_TP_12","PSI_TP_13","PSI_TP_14"),sep = ",",remove = T)

Cellcycle_A5SS_JC <- separate(Cellcycle_A5SS_JC, col = IncLevel2, into = c("PSI_TP_4","PSI_TP_5","PSI_TP_9","PSI_TP_10","PSI_TP_11"),sep = ",",remove = T)

Cellcycle_A5SS_JC[45:58] <- as.numeric(unlist(Cellcycle_A5SS_JC[45:58]))

Cellcycle_A5SS_JC = unite(Cellcycle_A5SS_JC,"Position",c(4:11),sep = ":",remove = T)
Cellcycle_A5SS_JC = na.omit(Cellcycle_A5SS_JC)
Cellcycle_A5SS_JC$PSIDiff <- (apply(Cellcycle_A5SS_JC[38:51], MARGIN =  1, f,))
Cellcycle_A5SS_JC = unite(Cellcycle_A5SS_JC,"EVENT",c(3,4),sep = "_", remove = T)
Cellcycle_A5SS_JC = subset(Cellcycle_A5SS_JC,select = c(53,3,2,5:7,23,24,8:10,25:27,11:13,
                                                    14:16,28,29,17:19,30:32,20:22,
                                                    37:39,46,47,40:42,48:50,43:45,36,54))
```




A5SS Filtering by average reads
```{r}
Cellcycle_A5SS_JC <- subset(Cellcycle_A5SS_JC,
                         apply(Cellcycle_A5SS_JC[c(4,18)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(5,19)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(6,20)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(7,21)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(8,22)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(9,23)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(10,24)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(11,25)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(12,26)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(13,27)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(14,28)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(15,29)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(16,30)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_A5SS_JC[c(17,31)], MARGIN =  1,mean)>=coverage)
```



MXE
```{r}
Cellcycle_MXE_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/MXE.MATS.JC.txt",header = T)
Cellcycle_MXE_JC <- as.data.frame(Cellcycle_MXE_JC)
Cellcycle_MXE_JC$Key <- paste(Cellcycle_MXE_JC$ID,Cellcycle_MXE_JC$GeneID,sep = "_")
rownames(Cellcycle_MXE_JC) <- Cellcycle_MXE_JC$Key
AS = as.data.frame(rep("A3SS",dim(Cellcycle_MXE_JC)[1]))
names(AS)[names(AS) == 'rep("A3SS", dim(Cellcycle_MXE_JC)[1])'] <- "Event"
Cellcycle_MXE_JC = cbind(Cellcycle_MXE_JC,AS)

Cellcycle_MXE_JC <- separate(Cellcycle_MXE_JC, col = IJC_SAMPLE_1, into = c("IJC_TP_1","IJC_TP_2","IJC_TP_3","IJC_TP_6","IJC_TP_7",
                                                                              "IJC_TP_8","IJC_TP_12","IJC_TP_13","IJC_TP_14"),sep = ",",remove = T)

Cellcycle_MXE_JC <- separate(Cellcycle_MXE_JC, col = SJC_SAMPLE_1, into = c("SJC_TP_1","SJC_TP_2","SJC_TP_3","SJC_TP_6","SJC_TP_7",
                                                                              "SJC_TP_8","SJC_TP_12","SJC_TP_13","SJC_TP_14"),sep = ",",remove = T)

Cellcycle_MXE_JC <- separate(Cellcycle_MXE_JC, col = IJC_SAMPLE_2, into = c("IJC_TP_4","IJC_TP_5","IJC_TP_9","IJC_TP_10","IJC_TP_11"),sep = ",",remove = T)

Cellcycle_MXE_JC <- separate(Cellcycle_MXE_JC, col = SJC_SAMPLE_2, into = c("SJC_TP_4","SJC_TP_5","SJC_TP_9","SJC_TP_10","SJC_TP_11"),sep = ",",remove = T)

Cellcycle_MXE_JC[15:42] <- as.numeric(unlist(Cellcycle_MXE_JC[15:42]))

Cellcycle_MXE_JC <- separate(Cellcycle_MXE_JC, col = IncLevel1, into = c("PSI_TP_1","PSI_TP_2","PSI_TP_3","PSI_TP_6","PSI_TP_7",
                                                                           "PSI_TP_8","PSI_TP_12","PSI_TP_13","PSI_TP_14"),sep = ",",remove = T)

Cellcycle_MXE_JC <- separate(Cellcycle_MXE_JC, col = IncLevel2, into = c("PSI_TP_4","PSI_TP_5","PSI_TP_9","PSI_TP_10","PSI_TP_11"),sep = ",",remove = T)

Cellcycle_MXE_JC[47:60] <- as.numeric(unlist(Cellcycle_MXE_JC[47:60]))

Cellcycle_MXE_JC = unite(Cellcycle_MXE_JC,"Position",c(4:13),sep = ":",remove = T)
Cellcycle_MXE_JC = na.omit(Cellcycle_MXE_JC)
Cellcycle_MXE_JC$PSIDiff <- (apply(Cellcycle_MXE_JC[38:51], MARGIN =  1, f,))
Cellcycle_MXE_JC = unite(Cellcycle_MXE_JC,"EVENT",c(3,4),sep = "_", remove = T)
Cellcycle_MXE_JC = subset(Cellcycle_MXE_JC,select = c(53,3,2,5:7,23,24,8:10,25:27,11:13,
                                                    14:16,28,29,17:19,30:32,20:22,
                                                    37:39,46,47,40:42,48:50,43:45,36,54))
```


MXE Filtering by average reads
```{r}
Cellcycle_MXE_JC <- subset(Cellcycle_MXE_JC,
                         apply(Cellcycle_MXE_JC[c(4,18)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(5,19)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(6,20)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(7,21)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(8,22)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(9,23)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(10,24)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(11,25)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(12,26)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(13,27)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(14,28)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(15,29)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(16,30)], MARGIN =  1,mean)>=coverage
                         &apply(Cellcycle_MXE_JC[c(17,31)], MARGIN =  1,mean)>=coverage)
```

Combining Events
```{r}
AS_TPevents <- rbind(Cellcycle_RI_JC,Cellcycle_SE_JC,Cellcycle_A3SS_JC,Cellcycle_A5SS_JC,Cellcycle_MXE_JC)
write.csv(AS_TPevents,"AS-nonorm-50counts.csv")

AS_TPeventsDiff = subset(AS_TPevents,PSIDiff>=0.1)
rownames(AS_TPeventsDiff) <- NULL
write.csv(AS_TPeventsDiff,"AS-nonorm-50counts-10perdiffPSI.csv")
```




