---
title: "ASElife50"
author: "Kwame Forbes"
date: "10/4/2022"
output: html_document
---

load Dependencies
```{r}
library(dplyr)
library(tidyr)
```

variables
```{r}
counts.variable = 100
```

Filtering Elife by 50 counts
```{r}
#RI Events
CC_RI_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/RI.MATS.JC.txt",header = T)
CC_RI_JC <- as.data.frame(CC_RI_JC)
CC_RI_JC$Key <- paste(CC_RI_JC$ID,CC_RI_JC$GeneID,sep = "_")
rownames(CC_RI_JC) <- CC_RI_JC$Key
AS = as.data.frame(rep("RI",dim(CC_RI_JC)[1]))
names(AS)[names(AS) == 'rep("RI", dim(CC_RI_JC)[1])'] <- "Event"
CC_RI_JC = cbind(CC_RI_JC,AS)

CC_RI_JC <- separate(CC_RI_JC, col = IJC_SAMPLE_1, into = c("IJC_TimePoint_1","IJC_TimePoint_2","IJC_TimePoint_3","IJC_TimePoint_6","IJC_TimePoint_7","IJC_TimePoint_8","IJC_TimePoint_12","IJC_TimePoint_13","IJC_TimePoint_14"),sep = ",",remove = T)
CC_RI_JC <- separate(CC_RI_JC, col = SJC_SAMPLE_1, into = c("SJC_TimePoint_1","SJC_TimePoint_2","SJC_TimePoint_3","SJC_TimePoint_6","SJC_TimePoint_7","SJC_TimePoint_8","SJC_TimePoint_12","SJC_TimePoint_13","SJC_TimePoint_14"),sep = ",",remove = T)
CC_RI_JC <- separate(CC_RI_JC, col = IJC_SAMPLE_2, into = c("IJC_TimePoint_4","IJC_TimePoint_5","IJC_TimePoint_9","IJC_TimePoint_10","IJC_TimePoint_11"),sep = ",",remove = T)
CC_RI_JC <- separate(CC_RI_JC, col = SJC_SAMPLE_2, into = c("SJC_TimePoint_4","SJC_TimePoint_5","SJC_TimePoint_9","SJC_TimePoint_10","SJC_TimePoint_11"),sep = ",",remove = T)
CC_RI_JC[11:40] <- as.numeric(unlist(CC_RI_JC[11:40]))

CC_RI_JC <- separate(CC_RI_JC, col = IncLevel1, into = c("IncLevel_TimePoint_1","IncLevel_TimePoint_2","IncLevel_TimePoint_3","IncLevel_TimePoint_6","IncLevel_TimePoint_7","IncLevel_TimePoint_8","IncLevel_TimePoint_12","IncLevel_TimePoint_13","IncLevel_TimePoint_14"),sep = ",",remove = T)
CC_RI_JC <- separate(CC_RI_JC, col = IncLevel2, into = c("IncLevel_TimePoint_4","IncLevel_TimePoint_5","IncLevel_TimePoint_9","IncLevel_TimePoint_10","IncLevel_TimePoint_11"),sep = ",",remove = T)
CC_RI_JC[45:58] <- as.numeric(unlist(CC_RI_JC[45:58]))

CC_RI_JC = unite(CC_RI_JC,"Position",c(4:11),sep = ":",remove = T)

CC_RI_JC50 = subset(CC_RI_JC,IJC_TimePoint_1+SJC_TimePoint_1&IJC_TimePoint_2+SJC_TimePoint_2&IJC_TimePoint_3+SJC_TimePoint_3&IJC_TimePoint_4+SJC_TimePoint_4&IJC_TimePoint_5+SJC_TimePoint_5&IJC_TimePoint_6+SJC_TimePoint_6&
                               IJC_TimePoint_7+SJC_TimePoint_7&IJC_TimePoint_8+SJC_TimePoint_8&IJC_TimePoint_9+SJC_TimePoint_9&IJC_TimePoint_10+SJC_TimePoint_10&IJC_TimePoint_11+SJC_TimePoint_11&IJC_TimePoint_12+SJC_TimePoint_12&
                               IJC_TimePoint_13+SJC_TimePoint_13&IJC_TimePoint_14+SJC_TimePoint_14>=counts.variable)


#SE Events
CC_SE_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/SE.MATS.JC.txt",header = T)
CC_SE_JC <- as.data.frame(CC_SE_JC)
CC_SE_JC$Key <- paste(CC_SE_JC$ID,CC_SE_JC$GeneID,sep = "_")
rownames(CC_SE_JC) <- CC_SE_JC$Key
AS = as.data.frame(rep("SE",dim(CC_SE_JC)[1]))
names(AS)[names(AS) == 'rep("SE", dim(CC_SE_JC)[1])'] <- "Event"
CC_SE_JC = cbind(CC_SE_JC,AS)

CC_SE_JC <- separate(CC_SE_JC, col = IJC_SAMPLE_1, into = c("IJC_TimePoint_1","IJC_TimePoint_2","IJC_TimePoint_3","IJC_TimePoint_6","IJC_TimePoint_7","IJC_TimePoint_8","IJC_TimePoint_12","IJC_TimePoint_13","IJC_TimePoint_14"),sep = ",",remove = T)
CC_SE_JC <- separate(CC_SE_JC, col = SJC_SAMPLE_1, into = c("SJC_TimePoint_1","SJC_TimePoint_2","SJC_TimePoint_3","SJC_TimePoint_6","SJC_TimePoint_7","SJC_TimePoint_8","SJC_TimePoint_12","SJC_TimePoint_13","SJC_TimePoint_14"),sep = ",",remove = T)
CC_SE_JC <- separate(CC_SE_JC, col = IJC_SAMPLE_2, into = c("IJC_TimePoint_4","IJC_TimePoint_5","IJC_TimePoint_9","IJC_TimePoint_10","IJC_TimePoint_11"),sep = ",",remove = T)
CC_SE_JC <- separate(CC_SE_JC, col = SJC_SAMPLE_2, into = c("SJC_TimePoint_4","SJC_TimePoint_5","SJC_TimePoint_9","SJC_TimePoint_10","SJC_TimePoint_11"),sep = ",",remove = T)
CC_SE_JC[11:40] <- as.numeric(unlist(CC_SE_JC[11:40]))

CC_SE_JC <- separate(CC_SE_JC, col = IncLevel1, into = c("IncLevel_TimePoint_1","IncLevel_TimePoint_2","IncLevel_TimePoint_3","IncLevel_TimePoint_6","IncLevel_TimePoint_7","IncLevel_TimePoint_8","IncLevel_TimePoint_12","IncLevel_TimePoint_13","IncLevel_TimePoint_14"),sep = ",",remove = T)
CC_SE_JC <- separate(CC_SE_JC, col = IncLevel2, into = c("IncLevel_TimePoint_4","IncLevel_TimePoint_5","IncLevel_TimePoint_9","IncLevel_TimePoint_10","IncLevel_TimePoint_11"),sep = ",",remove = T)
CC_SE_JC[45:58] <- as.numeric(unlist(CC_SE_JC[45:58]))

CC_SE_JC = unite(CC_SE_JC,"Position",c(4:11),sep = ":",remove = T)

CC_SE_JC50 = subset(CC_SE_JC,IJC_TimePoint_1+SJC_TimePoint_1&IJC_TimePoint_2+SJC_TimePoint_2&IJC_TimePoint_3+SJC_TimePoint_3&IJC_TimePoint_4+SJC_TimePoint_4&IJC_TimePoint_5+SJC_TimePoint_5&IJC_TimePoint_6+SJC_TimePoint_6&
                             IJC_TimePoint_7+SJC_TimePoint_7&IJC_TimePoint_8+SJC_TimePoint_8&IJC_TimePoint_9+SJC_TimePoint_9&IJC_TimePoint_10+SJC_TimePoint_10&IJC_TimePoint_11+SJC_TimePoint_11&IJC_TimePoint_12+SJC_TimePoint_12&
                             IJC_TimePoint_13+SJC_TimePoint_13&IJC_TimePoint_14+SJC_TimePoint_14>=counts.variable)


#A3SS Events
CC_A3SS_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/A3SS.MATS.JC.txt",header = T)
CC_A3SS_JC <- as.data.frame(CC_A3SS_JC)
CC_A3SS_JC$Key <- paste(CC_A3SS_JC$ID,CC_A3SS_JC$GeneID,sep = "_")
rownames(CC_A3SS_JC) <- CC_A3SS_JC$Key
AS = as.data.frame(rep("A3SS",dim(CC_A3SS_JC)[1]))
names(AS)[names(AS) == 'rep("A3SS", dim(CC_A3SS_JC)[1])'] <- "Event"
CC_A3SS_JC = cbind(CC_A3SS_JC,AS)

CC_A3SS_JC <- separate(CC_A3SS_JC, col = IJC_SAMPLE_1, into = c("IJC_TimePoint_1","IJC_TimePoint_2","IJC_TimePoint_3","IJC_TimePoint_6","IJC_TimePoint_7","IJC_TimePoint_8","IJC_TimePoint_12","IJC_TimePoint_13","IJC_TimePoint_14"),sep = ",",remove = T)
CC_A3SS_JC <- separate(CC_A3SS_JC, col = SJC_SAMPLE_1, into = c("SJC_TimePoint_1","SJC_TimePoint_2","SJC_TimePoint_3","SJC_TimePoint_6","SJC_TimePoint_7","SJC_TimePoint_8","SJC_TimePoint_12","SJC_TimePoint_13","SJC_TimePoint_14"),sep = ",",remove = T)
CC_A3SS_JC <- separate(CC_A3SS_JC, col = IJC_SAMPLE_2, into = c("IJC_TimePoint_4","IJC_TimePoint_5","IJC_TimePoint_9","IJC_TimePoint_10","IJC_TimePoint_11"),sep = ",",remove = T)
CC_A3SS_JC <- separate(CC_A3SS_JC, col = SJC_SAMPLE_2, into = c("SJC_TimePoint_4","SJC_TimePoint_5","SJC_TimePoint_9","SJC_TimePoint_10","SJC_TimePoint_11"),sep = ",",remove = T)
CC_A3SS_JC[11:40] <- as.numeric(unlist(CC_A3SS_JC[11:40]))

CC_A3SS_JC <- separate(CC_A3SS_JC, col = IncLevel1, into = c("IncLevel_TimePoint_1","IncLevel_TimePoint_2","IncLevel_TimePoint_3","IncLevel_TimePoint_6","IncLevel_TimePoint_7","IncLevel_TimePoint_8","IncLevel_TimePoint_12","IncLevel_TimePoint_13","IncLevel_TimePoint_14"),sep = ",",remove = T)
CC_A3SS_JC <- separate(CC_A3SS_JC, col = IncLevel2, into = c("IncLevel_TimePoint_4","IncLevel_TimePoint_5","IncLevel_TimePoint_9","IncLevel_TimePoint_10","IncLevel_TimePoint_11"),sep = ",",remove = T)
CC_A3SS_JC[45:58] <- as.numeric(unlist(CC_A3SS_JC[45:58]))

CC_A3SS_JC = unite(CC_A3SS_JC,"Position",c(4:11),sep = ":",remove = T)

CC_A3SS_JC50 = subset(CC_A3SS_JC,IJC_TimePoint_1+SJC_TimePoint_1&IJC_TimePoint_2+SJC_TimePoint_2&IJC_TimePoint_3+SJC_TimePoint_3&IJC_TimePoint_4+SJC_TimePoint_4&IJC_TimePoint_5+SJC_TimePoint_5&IJC_TimePoint_6+SJC_TimePoint_6&
                             IJC_TimePoint_7+SJC_TimePoint_7&IJC_TimePoint_8+SJC_TimePoint_8&IJC_TimePoint_9+SJC_TimePoint_9&IJC_TimePoint_10+SJC_TimePoint_10&IJC_TimePoint_11+SJC_TimePoint_11&IJC_TimePoint_12+SJC_TimePoint_12&
                             IJC_TimePoint_13+SJC_TimePoint_13&IJC_TimePoint_14+SJC_TimePoint_14>=counts.variable)


#A5SS Events
CC_A5SS_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/A5SS.MATS.JC.txt",header = T)
CC_A5SS_JC <- as.data.frame(CC_A5SS_JC)
CC_A5SS_JC$Key <- paste(CC_A5SS_JC$ID,CC_A5SS_JC$GeneID,sep = "_")
rownames(CC_A5SS_JC) <- CC_A5SS_JC$Key
AS = as.data.frame(rep("A5SS",dim(CC_A5SS_JC)[1]))
names(AS)[names(AS) == 'rep("A5SS", dim(CC_A5SS_JC)[1])'] <- "Event"
CC_A5SS_JC = cbind(CC_A5SS_JC,AS)

CC_A5SS_JC <- separate(CC_A5SS_JC, col = IJC_SAMPLE_1, into = c("IJC_TimePoint_1","IJC_TimePoint_2","IJC_TimePoint_3","IJC_TimePoint_6","IJC_TimePoint_7","IJC_TimePoint_8","IJC_TimePoint_12","IJC_TimePoint_13","IJC_TimePoint_14"),sep = ",",remove = T)
CC_A5SS_JC <- separate(CC_A5SS_JC, col = SJC_SAMPLE_1, into = c("SJC_TimePoint_1","SJC_TimePoint_2","SJC_TimePoint_3","SJC_TimePoint_6","SJC_TimePoint_7","SJC_TimePoint_8","SJC_TimePoint_12","SJC_TimePoint_13","SJC_TimePoint_14"),sep = ",",remove = T)
CC_A5SS_JC <- separate(CC_A5SS_JC, col = IJC_SAMPLE_2, into = c("IJC_TimePoint_4","IJC_TimePoint_5","IJC_TimePoint_9","IJC_TimePoint_10","IJC_TimePoint_11"),sep = ",",remove = T)
CC_A5SS_JC <- separate(CC_A5SS_JC, col = SJC_SAMPLE_2, into = c("SJC_TimePoint_4","SJC_TimePoint_5","SJC_TimePoint_9","SJC_TimePoint_10","SJC_TimePoint_11"),sep = ",",remove = T)
CC_A5SS_JC[11:40] <- as.numeric(unlist(CC_A5SS_JC[11:40]))

CC_A5SS_JC <- separate(CC_A5SS_JC, col = IncLevel1, into = c("IncLevel_TimePoint_1","IncLevel_TimePoint_2","IncLevel_TimePoint_3","IncLevel_TimePoint_6","IncLevel_TimePoint_7","IncLevel_TimePoint_8","IncLevel_TimePoint_12","IncLevel_TimePoint_13","IncLevel_TimePoint_14"),sep = ",",remove = T)
CC_A5SS_JC <- separate(CC_A5SS_JC, col = IncLevel2, into = c("IncLevel_TimePoint_4","IncLevel_TimePoint_5","IncLevel_TimePoint_9","IncLevel_TimePoint_10","IncLevel_TimePoint_11"),sep = ",",remove = T)
CC_A5SS_JC[45:58] <- as.numeric(unlist(CC_A5SS_JC[45:58]))

CC_A5SS_JC = unite(CC_A5SS_JC,"Position",c(4:11),sep = ":",remove = T)

CC_A5SS_JC50 = subset(CC_A5SS_JC,IJC_TimePoint_1+SJC_TimePoint_1&IJC_TimePoint_2+SJC_TimePoint_2&IJC_TimePoint_3+SJC_TimePoint_3&IJC_TimePoint_4+SJC_TimePoint_4&IJC_TimePoint_5+SJC_TimePoint_5&IJC_TimePoint_6+SJC_TimePoint_6&
                             IJC_TimePoint_7+SJC_TimePoint_7&IJC_TimePoint_8+SJC_TimePoint_8&IJC_TimePoint_9+SJC_TimePoint_9&IJC_TimePoint_10+SJC_TimePoint_10&IJC_TimePoint_11+SJC_TimePoint_11&IJC_TimePoint_12+SJC_TimePoint_12&
                             IJC_TimePoint_13+SJC_TimePoint_13&IJC_TimePoint_14+SJC_TimePoint_14>=counts.variable)




#MXE Events
CC_MXE_JC <- read.table("/pine/scr/k/w/kwamek/pengda_collab/RMATS-Cellcycle/MXE.MATS.JC.txt",header = T)
CC_MXE_JC <- as.data.frame(CC_MXE_JC)
CC_MXE_JC$Key <- paste(CC_MXE_JC$ID,CC_MXE_JC$GeneID,sep = "_")
rownames(CC_MXE_JC) <- CC_MXE_JC$Key
AS = as.data.frame(rep("MXE",dim(CC_MXE_JC)[1]))
names(AS)[names(AS) == 'rep("MXE", dim(CC_MXE_JC)[1])'] <- "Event"
CC_MXE_JC = cbind(CC_MXE_JC,AS)


CC_MXE_JC <- separate(CC_MXE_JC, col = IJC_SAMPLE_1, into = c("IJC_TimePoint_1","IJC_TimePoint_2","IJC_TimePoint_3","IJC_TimePoint_6","IJC_TimePoint_7","IJC_TimePoint_8","IJC_TimePoint_12","IJC_TimePoint_13","IJC_TimePoint_14"),sep = ",",remove = T)
CC_MXE_JC <- separate(CC_MXE_JC, col = SJC_SAMPLE_1, into = c("SJC_TimePoint_1","SJC_TimePoint_2","SJC_TimePoint_3","SJC_TimePoint_6","SJC_TimePoint_7","SJC_TimePoint_8","SJC_TimePoint_12","SJC_TimePoint_13","SJC_TimePoint_14"),sep = ",",remove = T)
CC_MXE_JC <- separate(CC_MXE_JC, col = IJC_SAMPLE_2, into = c("IJC_TimePoint_4","IJC_TimePoint_5","IJC_TimePoint_9","IJC_TimePoint_10","IJC_TimePoint_11"),sep = ",",remove = T)
CC_MXE_JC <- separate(CC_MXE_JC, col = SJC_SAMPLE_2, into = c("SJC_TimePoint_4","SJC_TimePoint_5","SJC_TimePoint_9","SJC_TimePoint_10","SJC_TimePoint_11"),sep = ",",remove = T)
CC_MXE_JC[15:42] <- as.numeric(unlist(CC_MXE_JC[15:42]))

CC_MXE_JC <- separate(CC_MXE_JC, col = IncLevel1, into = c("IncLevel_TimePoint_1","IncLevel_TimePoint_2","IncLevel_TimePoint_3","IncLevel_TimePoint_6","IncLevel_TimePoint_7","IncLevel_TimePoint_8","IncLevel_TimePoint_12","IncLevel_TimePoint_13","IncLevel_TimePoint_14"),sep = ",",remove = T)
CC_MXE_JC <- separate(CC_MXE_JC, col = IncLevel2, into = c("IncLevel_TimePoint_4","IncLevel_TimePoint_5","IncLevel_TimePoint_9","IncLevel_TimePoint_10","IncLevel_TimePoint_11"),sep = ",",remove = T)
CC_MXE_JC[47:60] <- as.numeric(unlist(CC_MXE_JC[47:60]))

CC_MXE_JC = unite(CC_MXE_JC,"Position",c(4:13),sep = ":",remove = T)

CC_MXE_JC50 = subset(CC_MXE_JC,IJC_TimePoint_1+SJC_TimePoint_1&IJC_TimePoint_2+SJC_TimePoint_2&IJC_TimePoint_3+SJC_TimePoint_3&IJC_TimePoint_4+SJC_TimePoint_4&IJC_TimePoint_5+SJC_TimePoint_5&IJC_TimePoint_6+SJC_TimePoint_6&
                             IJC_TimePoint_7+SJC_TimePoint_7&IJC_TimePoint_8+SJC_TimePoint_8&IJC_TimePoint_9+SJC_TimePoint_9&IJC_TimePoint_10+SJC_TimePoint_10&IJC_TimePoint_11+SJC_TimePoint_11&IJC_TimePoint_12+SJC_TimePoint_12&
                             IJC_TimePoint_13+SJC_TimePoint_13&IJC_TimePoint_14+SJC_TimePoint_14>=counts.variable)


ASevents50 <- rbind(CC_RI_JC50,CC_SE_JC50,CC_A3SS_JC50,CC_A5SS_JC50,CC_MXE_JC50)
ASevents50 <- na.omit(ASevents50)
```

```{r}

ASevents50_2 = unite(ASevents50,"EVENT",c(3,4),sep = "_", remove = F)
ASevents50_2 = subset(ASevents50_2,select = c(55,3,2,39:41,48:49,42:44,50:52,45:47))
rownames(ASevents50_2) <- NULL

#write.csv(ASevents50_2,"AS-nonorm-50counts.csv")
```





